### ISSUE TITLE
Mod only works on singleplayer and not multiplayer.

### ISSUE THREAD

**Issue by 88028802** [JamCoreModding/RightClickHarvest#12]
On singleplayer the mod works perfectly fine.
But on multiplayer, the sound of planting the crop plays but nothing changes.

**Comment by Jamalam360** [comment]
Does the multiplayer server have the mod installed?

**Comment by 88028802** [comment]
Hey, Thanks for the quick response.
I thought the mod was only client-side, with no server-side need for installation while playing on a server.
Ps. I truly like the mod you've created, it's really handy!
