### ISSUE TITLE
Question: If I harvest crop and  if I don't have any seeds, Is mod places a seed from nowhere

### ISSUE THREAD

**Issue by MuhammadrizoDeveloper** [JamCoreModding/RightClickHarvest#13]
Question: If I harvest the crop and don't have any seeds, Is mod places a seed from nowhere.

**Comment by Jamalam360** [comment]
Yeah that's an oversight I intended to fix - I'll get on it tonight.

**Comment by Jamalam360** [comment]
Yeah that's an oversight I intended to fix - I'll get on it tonight.

**Comment by Jamalam360** [comment]
thanks, fixed in 2.1.0
