### ISSUE TITLE
Server crashes when right-clicking

### ISSUE THREAD

**Issue by jericjan** [JamCoreModding/RightClickHarvest#15]
After the new update, the server just crashes when right-clicking on crops both while empty-handed and while holding an item.

[crash-2022-06-16_14.01.20-server.txt](https://github.com/JamCoreModding/RightClickHarvest/files/8919498/crash-2022-06-16_14.01.20-server.txt)

**Comment by Jamalam360** [comment]
Oops, sorry, 2.1.1 should be out momentarily to fix that

Thank you
