### ISSUE TITLE
[1.18] Harvesting wheat doesn't give any seeds

### ISSUE THREAD

**Issue by ocram9** [JamCoreModding/RightClickHarvest#16]
If you right click on wheat to harvest it, it replants the seeds but doesn't drop any left over seeds. If you harvest normally with left click you can get multiple seeds to replant.

**Comment by Jamalam360** [comment]
I'll take a look later, I recall this being an issue before so must be a regression I suppose

**Comment by KlutzyBubbles** [comment]
Any progress on this?

**Comment by Jamalam360** [comment]
Sorry been super busy, should be able to work on it tomorrow. I'll set a reminder so I don't forget

**Comment by Jamalam360** [comment]
I am uhhh....incredibly stupid. That bug was a big oversight from me lol

I'll release a fix tonight (maybe 6 hours ish, out right now)

**Comment by Jamalam360** [comment]
Thanks for reporting @ocram9 

@KlutzyBubbles @ocram9, V2.2.0 fixes this

**Comment by calloatti** [comment]
Can you fix this for the 1.18.2 version please?

**Comment by Jamalam360** [comment]
I'll look into it

**Comment by Jamalam360** [comment]
V2.2.1 has been backported for 1.18, fixed @calloatti

**Comment by Hi-ImKyle** [comment]
Either this still occurs in 1.20.1 or you managed to introduce the same bug :P

RCH version is 3.2.3, the last _latest_ version for 1.20.1

**Comment by Jamalam360** [comment]
@Hi-ImKyle I can't reproduce that. Both fabric and forge should have exactly the same harvesting code. Maybe another mod you have is messing with it

**Comment by Jamalam360** [comment]
Either way, 1.20.1 is out of support so there won't be any updates, but I can provide debugging help here
