### ISSUE TITLE
Intercepting HarvestScythe's scythe

### ISSUE THREAD

**Issue by Laifsyn** [JamCoreModding/RightClickHarvest#19]
Seems the mod is intercepting the right click harvest in area of the mod harvest Scythe (Fabric)

**Comment by Jamalam360** [comment]
The Harvest Scythe author actually originally suggested this compatibility, and suggested how it should be implemented. I have never personally played with harvest scythes, what's the issue?

**Comment by Jamalam360** [comment]
Wait ignore that I was getting confused

**Comment by Jamalam360** [comment]
I can't reproduce this, maybe you can give more information @Laifsyn? I am able to use the scythe by shift right clicking on the crops. Do you mean that when right clicking without shift, the scythe should be used?

**Comment by Laifsyn** [comment]
ithink it's the onlyHoe : true.


Since the scythe is technically not a hoe, it cancels the harvest of the scythe

**Comment by Laifsyn** [comment]
Well, if that's not the issue, then it would be something deeper like mods funking around which... would be a nightmare to find

**Comment by Jamalam360** [comment]
this is with `requireHoe` set to `true`, this looks correct to me https://imgur.com/a/Ms6nFDp

**Comment by Laifsyn** [comment]
It's so weird. In server I'm having issues, but singleplayer not

**Comment by Laifsyn** [comment]
Hands up* No clue what was happening. I thought it was because client didn't have RCH installed. I removed it, and no issues
ig I'll close this then
