### ISSUE TITLE
[Suggestion] Better tiered hoes have larger range

### ISSUE THREAD

**Issue by astridos2go** [JamCoreModding/RightClickHarvest#20]
I realize this may be out of the scope of this mod, but I was wondering if it would be possible to have hoes have a greater range of auto-harvesting?

My thoughts would be something like follows:
- Iron Hoe (and below): 1x1 range
- Diamond Hoe: 2x2 range
- Netherite Hoe: 3x3 range
Of course, this could be configurable for those who want to change the ranges or disable the feature entirely. 

I realize that this may not be possible to add while keeping the mod server-side only, which would be a bummer. 
But if it was possible, I think this would make the mod better, while also adding _some_ incentive for getting nicer hoes. 

I look forward to hearing your thoughts on this. Thank you!

**Comment by Jamalam360** [comment]
That's an interesting idea, I'm going to ask around and gather some other people's thoughts on this

**Comment by Platymemo** [comment]
dewit. Also, would be totally possible serverside so no worries there

**Comment by Jamalam360** [comment]
This'll be released in 3.0.0 tonight :)
