### ISSUE TITLE
fortune

### ISSUE THREAD

**Issue by An0yim0us666** [JamCoreModding/RightClickHarvest#21]
according to some post i saw here fortune should work in version 2.2.0 of the mod but im here in 2.2.1 mc1.18.2 and furtune doesnt seem to work...

**Comment by Jamalam360** [comment]
Sorry, I'm not sure how that happened. I'm backporting V3.0.0 to 1.18, it should be released soon.

**Comment by Jamalam360** [comment]
Thanks for reporting.

**Comment by An0yim0us666** [comment]
thank you
