### ISSUE TITLE
No config file generated, config file values ignored, version 3.0.1

### ISSUE THREAD

**Issue by shaneknysh** [JamCoreModding/RightClickHarvest#23]
Running version 3.0.1 with lib 0.4.4 the config/rightclickharvest,json file is not generated. 

Creating the file manually has no effect.

**Comment by Jamalam360** [comment]
Errrrrr that's concerning. Can you post a latest.log please?

**Comment by shaneknysh** [comment]
sure but there is no error generated from rightclickharvest just an error from croptopia.

[latest.log](https://gist.github.com/shaneknysh/1831b81f97af78c1b24e878b42bad2b0)

**Comment by Jamalam360** [comment]
RightClickHarvest is a fabric mod, from a glance of the log it looks like you're running forge

**Comment by shaneknysh** [comment]
manually created config

```
{
    "requireHoe": "true",
    "harvestInRadius": "true",
    "useHunger": "false"
}
```

**Comment by shaneknysh** [comment]
ah weird thing is right click is working when I add the mod!

thanks!

**Comment by Jamalam360** [comment]
Maybe some other mod like is adding it, no worries

**Comment by shaneknysh** [comment]
Looks like curseforge once again returned a fabric mod when searching for forge only ... :(
